env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 7
  sourceType: module
plugins:
  - react
ignorePatterns:
  - 'node_modules/'
  - 'build/'
  - 'src-old/'
rules: { "react/jsx-filename-extension": [0] }
settings:
  react:
    version: 'latest'
