BEGIN;

DROP TABLE IF EXISTS conversation CASCADE;

CREATE TABLE conversation (
    id SERIAL PRIMARY KEY,
    uniqueId VARCHAR NOT NULL UNIQUE,
    dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE messages (
    id SERIAL PRIMARY KEY,
    conversation_id INT REFERENCES conversation(id) ON DELETE CASCADE,
    chat VARCHAR NOT NULL,
    dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
